-- ---------------------------------------------------------------------------
-- The quote id becomes what it should always have been: a number the database
-- issues.
--
-- It was a string minted in the browser, from when the app worked offline and
-- had to name a record before any server saw it. Nothing has worked that way
-- since everything moved behind the server, and a text key invented by a page
-- is not how a row is identified.
--
-- New ids are handed out in the order the quotes were created, so 2026-001
-- through 2026-010 stay exactly the numbers they are today. From here the
-- quote number simply is the id, and the two can never disagree again.
--
-- Identity is "by default" rather than "always" so a backup can be restored
-- with its original ids; the sequence is then set past the highest restored
-- value, which is the setval the restore does for itself.
-- ---------------------------------------------------------------------------

alter table public.quotes add column if not exists id_num bigint;

with ordered as (
  select id, row_number() over (order by seq) as rn from public.quotes
)
update public.quotes q set id_num = o.rn from ordered o where o.id = q.id;

alter table public.quotes drop constraint quotes_pkey;
alter table public.quotes drop column id;
alter table public.quotes rename column id_num to id;
alter table public.quotes alter column id set not null;
alter table public.quotes add primary key (id);
alter table public.quotes alter column id add generated by default as identity;

select setval(pg_get_serial_sequence('public.quotes', 'id'),
              coalesce((select max(id) from public.quotes), 0) + 1,
              false);

-- The id lived in the data blob as well. One home, as with the status.
update public.quotes set data = data - 'id';

-- The number follows from the id, so the database issues it rather than the
-- browser proposing one and hoping it is free. Written once, at insert, and
-- never recomputed: a quote created in 2026 keeps its 2026 next January.
create or replace function public.set_quote_no()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.quote_no is null or new.quote_no = '' then
    new.quote_no := to_char(coalesce(new.created_at, now()), 'YYYY')
                    || '-' || lpad(new.id::text, 3, '0');
  end if;
  return new;
end $$;

drop trigger if exists quotes_number on public.quotes;
create trigger quotes_number
  before insert on public.quotes
  for each row execute function public.set_quote_no();

-- Existing rows keep the numbers they already have.
update public.quotes
   set quote_no = coalesce(nullif(quote_no, ''), data->>'quoteNo')
 where quote_no is null or quote_no = '';

-- And the number, like the id and the status, now lives in one place.
update public.quotes set data = data - 'quoteNo';

-- seq only ever ordered the list, and the list orders itself by save date now.
alter table public.quotes drop column if exists seq;

-- ---------------------------------------------------------------------------
-- The columns that were copies.
--
-- Each of these was written from the data blob on every save and read by
-- nothing. A second copy of a fact that already has a home is how the status
-- came to disagree with itself twice, and there is no reason to keep eight
-- more of them waiting to do the same.
-- ---------------------------------------------------------------------------
drop index if exists quotes_owner_date;
alter table public.quotes
  drop column if exists customer,
  drop column if exists contact,
  drop column if exists notes,
  drop column if exists price,
  drop column if exists tip,
  drop column if exists cost,
  drop column if exists total_km,
  drop column if exists first_date,
  drop column if exists origin;

-- A stranger's request cannot name columns that no longer exist.
create or replace function public.request_quote(payload jsonb, secret text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  the_owner uuid;
  recent    int;
  clean     jsonb;
  want      text;
  new_id    bigint;
begin
  select owner, request_secret into the_owner, want from public.config where id;
  if the_owner is null then raise exception 'no driver configured'; end if;
  if want is null or secret is distinct from want then
    raise exception 'that request did not come from the form';
  end if;

  select count(*) into recent
    from public.quotes
   where status = 'requested' and created_at > now() - interval '1 minute';
  if recent >= 5 then raise exception 'too many requests, try again shortly'; end if;

  if coalesce(trim(payload->>'customer'), '') = '' then
    raise exception 'a name is required';
  end if;
  if length(payload::text) > 8000 then
    raise exception 'that request is too large';
  end if;

  clean := jsonb_build_object(
    'customer', left(trim(payload->>'customer'), 120),
    'contact',  left(coalesce(trim(payload->>'contact'), ''), 60),
    'notes',    left(coalesce(trim(payload->>'note'), ''), 1000),
    'lang',     case when payload->>'lang' in ('pt','en','fr') then payload->>'lang' else 'pt' end,
    'origin',   'customer',
    'savedAt',  to_jsonb(now()),
    'trips',    coalesce(jsonb_path_query_first(payload, '$.trips ? (@.type() == "array")'), '[]'::jsonb),
    'pax',      coalesce(jsonb_path_query_first(payload, '$.pax  ? (@.type() == "object")'), '{}'::jsonb),
    'gear',     coalesce(jsonb_path_query_first(payload, '$.gear ? (@.type() == "object")'), '{}'::jsonb),
    'bags',     coalesce(jsonb_path_query_first(payload, '$.bags ? (@.type() == "object")'), '{}'::jsonb)
  );

  if jsonb_array_length(clean -> 'trips') > 4 then
    raise exception 'too many legs in that request';
  end if;

  insert into public.quotes (owner, status, data)
  values (the_owner, 'requested', clean)
  returning id into new_id;

  return (select share_token from public.quotes where id = new_id);
end $$;

revoke all on function public.request_quote(jsonb, text) from public;
grant execute on function public.request_quote(jsonb, text) to anon, authenticated;
