-- Transfer Meter — Supabase schema
--
-- Two audiences with very different rights:
--   you        signed in, own every row, full access
--   a customer not signed in, holds only a link, may read ONE quote and
--              answer it — nothing else
--
-- The customer never touches these tables directly. Access is revoked and
-- given back through two security-definer functions that take the link's
-- token, so the boundary is enforced by Postgres rather than by client code.

-- ---------------------------------------------------------------- quotes ---
create table if not exists public.quotes (
  -- The database issues the id, and the quote number follows from it: id 11 is
  -- quote 2026-011. By default rather than always, so a backup can be restored
  -- with the ids it was taken with.
  id           bigint generated by default as identity primary key,
  owner        uuid not null references auth.users(id) on delete cascade,
  quote_no     text,                                -- set by the trigger below
  -- Where the quote came from, and who is waiting on whom:
  --   draft      you saved it, not sent yet          → you
  --   requested  the customer asked for it           → you
  --   sent       you sent it, awaiting their answer  → them
  --   approved   they accepted
  --   declined   they said no, or you turned down a request
  status       text not null default 'draft'
                 check (status in ('draft','requested','sent','approved','declined')),
  -- Everything the quote says. Nothing in here is mirrored in a column: the
  -- four things a column owns -- id, number, status, token -- are not in it.
  data         jsonb  not null,
  share_token  text not null unique
                 default replace(gen_random_uuid()::text, '-', ''),
  answered_at  timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  unique (owner, quote_no)
);

-- The number is the id, with the year it was created in front. Written once,
-- at insert, so a quote created in 2026 keeps its 2026 next January.
create or replace function public.set_quote_no()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.quote_no is null or new.quote_no = '' then
    new.quote_no := to_char(coalesce(new.created_at, now()), 'YYYY')
                    || '-' || lpad(new.id::text, 3, '0');
  end if;
  return new;
end $$;

drop trigger if exists quotes_number on public.quotes;
create trigger quotes_number
  before insert on public.quotes
  for each row execute function public.set_quote_no();

create index if not exists quotes_owner_status on public.quotes (owner, status);

-- Who new customer requests belong to. One driver, one row.
create table if not exists public.config (
  id    boolean primary key default true check (id),
  owner uuid not null references auth.users(id) on delete cascade
);

-- Shared with the request form's server route and nothing else. It is not a
-- privilege: it only proves a request came through the route that checked
-- Turnstile, rather than straight at the API with the public key everyone has.
alter table public.config add column if not exists request_secret text;
update public.config
   set request_secret = encode(gen_random_bytes(24), 'hex')
 where request_secret is null;
alter table public.config enable row level security;
drop policy if exists "owner reads config" on public.config;
create policy "owner reads config" on public.config
  for select using (auth.uid() = owner);

-- --------------------------------------------------- settings & distances ---
create table if not exists public.settings (
  owner      uuid primary key references auth.users(id) on delete cascade,
  data       jsonb not null default '{}'::jsonb,     -- car, fuel, bands, your details
  draft      jsonb not null default '{}'::jsonb,     -- the trip open in the editor
  -- Counts up on every write of `data`. A tab sends back the number it loaded,
  -- and a write whose number is behind is refused rather than applied: an old
  -- tab cannot quietly undo a setting changed somewhere else, which is how the
  -- price bands and the road factor came back an hour after being changed.
  version    bigint not null default 0,
  updated_at timestamptz not null default now()
);

alter table public.settings add column if not exists version bigint not null default 0;

create table if not exists public.learned (
  owner uuid not null references auth.users(id) on delete cascade,
  pair  text not null,                               -- "place a|place b", sorted
  km    numeric not null,
  primary key (owner, pair)
);

-- ------------------------------------------------------------------- rls ---
alter table public.quotes   enable row level security;
alter table public.settings enable row level security;
alter table public.learned  enable row level security;

-- You, signed in, own your rows and nothing else.
drop policy if exists "owner reads own quotes" on public.quotes;
create policy "owner reads own quotes" on public.quotes
  for select using (auth.uid() = owner);
drop policy if exists "owner writes own quotes" on public.quotes;
create policy "owner writes own quotes" on public.quotes
  for insert with check (auth.uid() = owner);
drop policy if exists "owner updates own quotes" on public.quotes;
create policy "owner updates own quotes" on public.quotes
  for update using (auth.uid() = owner) with check (auth.uid() = owner);
drop policy if exists "owner deletes own quotes" on public.quotes;
create policy "owner deletes own quotes" on public.quotes
  for delete using (auth.uid() = owner);

drop policy if exists "owner owns settings" on public.settings;
create policy "owner owns settings" on public.settings
  for all using (auth.uid() = owner) with check (auth.uid() = owner);
drop policy if exists "owner owns learned" on public.learned;
create policy "owner owns learned" on public.learned
  for all using (auth.uid() = owner) with check (auth.uid() = owner);

-- Anonymous visitors get no table access at all.
-- Supabase grants anon full table privileges by default; take them all back.
-- RLS would still refuse, but the grant should not be there to begin with.
revoke all on public.quotes, public.settings, public.learned, public.config from anon;
revoke all on all tables in schema public from anon;

-- ------------------------------------------------- customer asks for one ---
-- A stranger may create a request and nothing else. They cannot choose the
-- price, the status, or whose books it lands in — this function decides all
-- three. What comes back is only the token for following their own request.
create or replace function public.request_quote(payload jsonb, secret text)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  the_owner uuid;
  recent    int;
  clean     jsonb;
  want      text;
  new_id    bigint;
begin
  select owner, request_secret into the_owner, want from public.config where id;
  if the_owner is null then raise exception 'no driver configured'; end if;
  if want is null or secret is distinct from want then
    raise exception 'that request did not come from the form';
  end if;

  select count(*) into recent
    from public.quotes
   where status = 'requested' and created_at > now() - interval '1 minute';
  if recent >= 5 then raise exception 'too many requests, try again shortly'; end if;

  if coalesce(trim(payload->>'customer'), '') = '' then
    raise exception 'a name is required';
  end if;
  if length(payload::text) > 8000 then
    raise exception 'that request is too large';
  end if;

  clean := jsonb_build_object(
    'customer', left(trim(payload->>'customer'), 120),
    'contact',  left(coalesce(trim(payload->>'contact'), ''), 60),
    'notes',    left(coalesce(trim(payload->>'note'), ''), 1000),
    'lang',     case when payload->>'lang' in ('pt','en','fr') then payload->>'lang' else 'pt' end,
    'origin',   'customer',
    'savedAt',  to_jsonb(now()),
    'trips',    coalesce(jsonb_path_query_first(payload, '$.trips ? (@.type() == "array")'), '[]'::jsonb),
    'pax',      coalesce(jsonb_path_query_first(payload, '$.pax  ? (@.type() == "object")'), '{}'::jsonb),
    'gear',     coalesce(jsonb_path_query_first(payload, '$.gear ? (@.type() == "object")'), '{}'::jsonb),
    'bags',     coalesce(jsonb_path_query_first(payload, '$.bags ? (@.type() == "object")'), '{}'::jsonb)
  );

  if jsonb_array_length(clean -> 'trips') > 4 then
    raise exception 'too many legs in that request';
  end if;

  insert into public.quotes (owner, status, data)
  values (the_owner, 'requested', clean)
  returning id into new_id;

  return (select share_token from public.quotes where id = new_id);
end $$;

revoke all on function public.request_quote(jsonb, text) from public;
grant execute on function public.request_quote(jsonb, text) to anon, authenticated;

-- --------------------------------------------------------------- touch ------
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;

drop trigger if exists quotes_touch on public.quotes;
create trigger quotes_touch before update on public.quotes
  for each row execute function public.touch_updated_at();


-- Self-provisioning, then closed.
--
-- The first account created becomes the owner and is written into config, and
-- every attempt after it is refused. Nobody who finds the site can register,
-- whether the account is made here or in the dashboard.

create or replace function public.claim_first_account()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare existing int;
begin
  select count(*) into existing from auth.users where id <> new.id;

  if existing > 0 then
    raise exception 'This installation already has an owner.'
      using errcode = '42501';
  end if;

  -- The first account owns the data, and customer requests land in its books.
  insert into public.config (id, owner) values (true, new.id)
    on conflict (id) do update set owner = excluded.owner;

  return new;
end $$;

drop trigger if exists claim_first_account on auth.users;
create trigger claim_first_account
  after insert on auth.users
  for each row execute function public.claim_first_account();


-- Let a customer read and answer their own quote, with no table access.
--
-- What they may see is decided by the application when it saves, and stored in
-- What a customer's link opens: the quote as it stands, and the few settings
-- their copy prints. Never the home address, the fuel cost, the tip or the
-- notes. The app decides what to show from this, using the same function the
-- PDF uses, so the page and the document cannot disagree.
--
-- It returns the quote, not a stored copy of it. A copy is only ever right at
-- the moment it was written: change a price and every link already in a
-- customer's hands went on showing the old one.

create or replace function public.quote_by_token(token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  q public.quotes%rowtype;
  s jsonb;
begin
  select * into q from public.quotes where share_token = token;
  if not found then return null; end if;

  -- A draft has not been sent to anyone; it should not be readable yet.
  if q.status = 'draft' then return null; end if;

  -- Only what their copy prints. Never homeName, homeLat or homeLng, never the
  -- fuel figures, never the price bands.
  select jsonb_build_object(
           'bizName',  coalesce(data->>'bizName', ''),
           'bizPhone', coalesce(data->>'bizPhone', ''),
           'bizWhats', coalesce(data->>'bizWhats', ''),
           'seats',    coalesce((data->>'seats')::int, 7))
    into s
    from public.settings where owner = q.owner;

  return jsonb_build_object(
    'quote',       q.data,
    'id',          q.id,
    'quoteNo',     q.quote_no,
    'status',      q.status,
    'answered_at', q.answered_at,
    'settings',    coalesce(s, '{}'::jsonb));
end $$;

drop function if exists public.answer_quote(text, text);
create function public.answer_quote(token text, answer text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare q public.quotes%rowtype;
begin
  if answer not in ('approved','declined') then
    raise exception 'answer must be approved or declined';
  end if;

  -- The status lives in this column and nowhere else. It used to be copied
  -- into data as well, the two drifted, and an answer that reached only one of
  -- them was either invisible or silently overwritten. The driver's app reads
  -- this column now, and its saves do not carry a status at all.
  update public.quotes
     set status      = answer,
         answered_at = now(),
         updated_at  = now()
   where share_token = token
     and status in ('sent','approved','declined')   -- never a draft or a request
  returning * into q;

  if not found then raise exception 'that quote is not awaiting an answer'; end if;

  return jsonb_build_object('status', q.status, 'answered_at', q.answered_at);
end $$;

revoke all on function public.quote_by_token(text) from public;
revoke all on function public.answer_quote(text, text) from public;
grant execute on function public.quote_by_token(text) to anon, authenticated;
grant execute on function public.answer_quote(text, text) to anon, authenticated;


-- ---------------------------------------------------------------------------
-- A customer correcting their own details.
--
-- They know how many of them there are and what they are carrying better than
-- the driver guessing on the phone, so the link lets them fix it. Deliberately
-- narrow: counts only, on a quote that is still awaiting an answer, and every
-- key and value checked here rather than trusted from the browser. Nothing
-- about price, dates, addresses or status can be reached through it.
-- ---------------------------------------------------------------------------
create or replace function public.update_quote_counts(token text, counts jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  q      public.quotes%rowtype;
  clean  jsonb := '{}'::jsonb;
  grp    text;
  key    text;
  val    numeric;
  allowed constant jsonb := jsonb_build_object(
    'pax',  jsonb_build_array('adults','children','infants'),
    'gear', jsonb_build_array('infantSeat','carSeat','booster'),
    'bags', jsonb_build_array('checked','carry','backpack','stroller','crib','other')
  );
begin
  if jsonb_typeof(counts) is distinct from 'object' then
    raise exception 'counts must be an object';
  end if;

  -- Keep only keys this function recognises, as whole numbers within reach of
  -- a car. Anything else is dropped rather than argued with.
  for grp in select jsonb_object_keys(allowed) loop
    if counts ? grp then
      if jsonb_typeof(counts -> grp) is distinct from 'object' then
        raise exception '% must be an object', grp;
      end if;
      -- jsonb_set only ever creates the final key, so the group object has to
      -- exist before a value can be written inside it. Without this the writes
      -- vanish and the update looks like it worked.
      if not (clean ? grp) then
        clean := clean || jsonb_build_object(grp, '{}'::jsonb);
      end if;
      for key in select jsonb_array_elements_text(allowed -> grp) loop
        if (counts -> grp) ? key then
          begin
            val := (counts -> grp ->> key)::numeric;
          exception when others then
            raise exception 'bad value for %.%', grp, key;
          end;
          if val < 0 or val > 20 or val <> floor(val) then
            raise exception 'bad value for %.%', grp, key;
          end if;
          clean := jsonb_set(clean, array[grp, key], to_jsonb(floor(val)::int), true);
        end if;
      end loop;
    end if;
  end loop;

  update public.quotes
     set data = data
              || jsonb_build_object(
                   'pax',  coalesce(nullif(clean -> 'pax',  '{}'::jsonb), data -> 'pax'),
                   'gear', coalesce(nullif(clean -> 'gear', '{}'::jsonb), data -> 'gear'),
                   'bags', coalesce(nullif(clean -> 'bags', '{}'::jsonb), data -> 'bags'),
                   'customerEditedAt', to_jsonb(now())
                 ),
         updated_at = now()
   where share_token = token
     and status = 'sent'          -- only while it is still awaiting an answer
  returning * into q;

  if not found then
    raise exception 'that quote is not open for changes';
  end if;

  -- Read back from the quote itself, which is now the only copy of it.
  return jsonb_build_object('xc', jsonb_build_object(
    'pax',  coalesce(q.data -> 'pax',  '{}'::jsonb),
    'gear', coalesce(q.data -> 'gear', '{}'::jsonb),
    'bags', coalesce(q.data -> 'bags', '{}'::jsonb)));
end $$;

revoke all on function public.update_quote_counts(text, jsonb) from public;
grant execute on function public.update_quote_counts(text, jsonb) to anon, authenticated;


-- ------------------------------------------------- after a restore ---------
-- A restore writes ids the database did not issue, and an identity column does
-- not advance for those, so the next new quote would collide with a restored
-- one. This puts the sequence past the highest id that exists.
create or replace function public.sync_quote_ids()
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare top bigint;
begin
  -- Only ever the caller's own rows decide it, and only the owner may call it.
  select coalesce(max(id), 0) into top from public.quotes where owner = auth.uid();
  if auth.uid() is null then raise exception 'sign in first'; end if;
  return setval(pg_get_serial_sequence('public.quotes', 'id'),
                greatest(top, (select coalesce(max(id), 0) from public.quotes)) + 1,
                false);
end $$;

revoke all on function public.sync_quote_ids() from public;
grant execute on function public.sync_quote_ids() to authenticated;


-- ---------------------------------------------------------------------------
-- The stored copy of the customer's view, removed.
--
-- It was written whenever a quote was saved and read when a customer opened
-- their link, so it was right at the moment of writing and only then. The view
-- is shaped from the quote on every read now; there is nothing left to go
-- stale. Safe to re-run: the column may already be gone.
-- ---------------------------------------------------------------------------
alter table public.quotes drop column if exists customer_view;
